import Head from 'next/head';
import Navbar from '../components/Navbar';
import Banner from '../components/Banner';


export default function Home() {
  return (
    <>
      <Head>
        <title>Shoppers.com | Save Money. Live Better</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/smallico.ico" />
      </Head>
      <main className='bg-lightBlue '>
        <div className='max-w-contentContainer mx-auto bg-white'>
          <Navbar/>
          <Banner/>
        </div>
      </main>
    </>
  )
}
