import Head from 'next/head';
import Navbar from '../components/Navbar';


export default function Home() {
  return (
    <>
      <Head>
        <title>Shopers.com | Save Money. Live Better</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/smallico.ico" />
      </Head>
      <main>
        <Navbar/>
      </main>
    </>
  )
}
